apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAMESPACE}-sa
  namespace: ${NAMESPACE}
  annotations:
    # Hardcoded: GitLab Settings WORKLOAD_CLIENT_ID has typo "I" prefix
    azure.workload.identity/client-id: "966176be-711b-4f2f-8b80-dce08b14a8e2"