apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-configmap
  namespace: ${NAMESPACE}
data:
  # Required for bootstrap - Key Vault access
  AZURE_KEY_VAULT_NAME: "${AKS_KV_NAME}"
  AZURE_TENANT_ID: "${TENANT_ID}"